disabled_rules:
- force_cast
- function_body_length
- identifier_name
- large_tuple
- nesting
- multiple_closures_with_trailing_closure

included:
- LongWeekend
- LongWeekendTests

excluded:
- Pods/
- Carthage/
- vender/

line_length: 300

cyclomatic_complexity: 15
