disabled_rules:
- force_cast
- function_body_length
- identifier_name
- large_tuple
- nesting
- multiple_closures_with_trailing_closure

excluded:
- Pods/
- Carthage/
- vender/

line_length: 300

cyclomatic_complexity: 15

variable_name:
  max_length:
    warning: 60
    error: 80
  min_length:
    warning: 1
    error: 0
